// <auto-generated />
using System;
using MedIapp_API.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedIapp_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240611022626_AlimentarDBPaciente10registros")]
    partial class AlimentarDBPaciente10registros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedIapp_API.Modelos.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Examen")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ExamenNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExamenTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identificación")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Pérez",
                            Direccion = "Calle Falsa 123",
                            Email = "juan.perez@example.com",
                            Examen = new byte[] { 32, 32 },
                            ExamenNombre = "examen.pdf",
                            ExamenTipo = "application/pdf",
                            FechaNacimiento = new DateTime(1990, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificación = "DNI12345678",
                            Nombre = "Juan",
                            Observacion = "Paciente con alergia a la penicilina",
                            Telefono = "123456789"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Pérez",
                            Direccion = "Calle Falsa 123",
                            Email = "juan.perez@example.com",
                            Examen = new byte[] { 32, 32 },
                            ExamenNombre = "examen.pdf",
                            ExamenTipo = "application/pdf",
                            FechaNacimiento = new DateTime(1990, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificación = "DNI12345678",
                            Nombre = "Pepito",
                            Observacion = "Paciente con alergia a la penicilina",
                            Telefono = "123456789"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "García",
                            Direccion = "Av. Siempre Viva 742",
                            Email = "ana.garcia@example.com",
                            Examen = new byte[] { 32, 33 },
                            ExamenNombre = "examen1.pdf",
                            ExamenTipo = "application/pdf",
                            FechaNacimiento = new DateTime(1992, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificación = "DNI12345679",
                            Nombre = "Ana",
                            Observacion = "Paciente con diabetes",
                            Telefono = "987654321"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Mendoza",
                            Direccion = "Calle Luna 123",
                            Email = "carlos.mendoza@example.com",
                            Examen = new byte[] { 32, 34 },
                            ExamenNombre = "examen2.pdf",
                            ExamenTipo = "application/pdf",
                            FechaNacimiento = new DateTime(1988, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificación = "DNI12345680",
                            Nombre = "Carlos",
                            Observacion = "Alergia a la penicilina",
                            Telefono = "234567890"
                        },
                        new
                        {
                            Id = 5,
                            Apellido = "López",
                            Direccion = "Calle Flores 456",
                            Email = "maria.lopez@example.com",
                            Examen = new byte[] { 32, 35 },
                            ExamenNombre = "examen3.pdf",
                            ExamenTipo = "application/pdf",
                            FechaNacimiento = new DateTime(1985, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificación = "DNI12345681",
                            Nombre = "María",
                            Observacion = "Hipertensión",
                            Telefono = "345678901"
                        },
                        new
                        {
                            Id = 6,
                            Apellido = "Martínez",
                            Direccion = "Calle Sol 789",
                            Email = "jose.martinez@example.com",
                            Examen = new byte[] { 32, 36 },
                            ExamenNombre = "examen4.pdf",
                            ExamenTipo = "application/pdf",
                            FechaNacimiento = new DateTime(1975, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificación = "DNI12345682",
                            Nombre = "José",
                            Observacion = "Paciente asmático",
                            Telefono = "456789012"
                        },
                        new
                        {
                            Id = 7,
                            Apellido = "Ramírez",
                            Direccion = "Calle Estrella 321",
                            Email = "lucia.ramirez@example.com",
                            Examen = new byte[] { 32, 37 },
                            ExamenNombre = "examen5.pdf",
                            ExamenTipo = "application/pdf",
                            FechaNacimiento = new DateTime(2000, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificación = "DNI12345683",
                            Nombre = "Lucía",
                            Observacion = "Paciente con migrañas",
                            Telefono = "567890123"
                        },
                        new
                        {
                            Id = 8,
                            Apellido = "Gómez",
                            Direccion = "Calle Nube 654",
                            Email = "pedro.gomez@example.com",
                            Examen = new byte[] { 32, 38 },
                            ExamenNombre = "examen6.pdf",
                            ExamenTipo = "application/pdf",
                            FechaNacimiento = new DateTime(1999, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificación = "DNI12345684",
                            Nombre = "Pedro",
                            Observacion = "Paciente con hipercolesterolemia",
                            Telefono = "678901234"
                        },
                        new
                        {
                            Id = 9,
                            Apellido = "Vega",
                            Direccion = "Calle Mar 987",
                            Email = "clara.vega@example.com",
                            Examen = new byte[] { 32, 39 },
                            ExamenNombre = "examen7.pdf",
                            ExamenTipo = "application/pdf",
                            FechaNacimiento = new DateTime(1991, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificación = "DNI12345685",
                            Nombre = "Clara",
                            Observacion = "Paciente con tiroides",
                            Telefono = "789012345"
                        },
                        new
                        {
                            Id = 10,
                            Apellido = "Díaz",
                            Direccion = "Calle Bosque 258",
                            Email = "hugo.diaz@example.com",
                            Examen = new byte[] { 32, 40 },
                            ExamenNombre = "examen8.pdf",
                            ExamenTipo = "application/pdf",
                            FechaNacimiento = new DateTime(1982, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificación = "DNI12345686",
                            Nombre = "Hugo",
                            Observacion = "Paciente con insuficiencia renal",
                            Telefono = "890123456"
                        },
                        new
                        {
                            Id = 11,
                            Apellido = "Blanco",
                            Direccion = "Calle Arcoiris 159",
                            Email = "sofia.blanco@example.com",
                            Examen = new byte[] { 32, 41 },
                            ExamenNombre = "examen9.pdf",
                            ExamenTipo = "application/pdf",
                            FechaNacimiento = new DateTime(1978, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificación = "DNI12345687",
                            Nombre = "Sofía",
                            Observacion = "Paciente con artritis",
                            Telefono = "901234567"
                        },
                        new
                        {
                            Id = 12,
                            Apellido = "Pérez",
                            Direccion = "Calle Río 852",
                            Email = "luis.perez@example.com",
                            Examen = new byte[] { 32, 48 },
                            ExamenNombre = "examen10.pdf",
                            ExamenTipo = "application/pdf",
                            FechaNacimiento = new DateTime(1987, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificación = "DNI12345688",
                            Nombre = "Luis",
                            Observacion = "Paciente con esclerosis múltiple",
                            Telefono = "012345678"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
